apiVersion: v1
kind: ServiceAccount
metadata:
  name: lwp-backend
  namespace: lwp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lwp-backend
  namespace: lwp
rules:
  - apiGroups: [""]
    resources: [pods, services]
    verbs: [get, list, create, delete, watch]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lwp-backend
  namespace: lwp
subjects:
  - kind: ServiceAccount
    name: lwp-backend
    namespace: lwp
roleRef:
  kind: Role
  name: lwp-backend
  apiGroup: rbac.authorization.k8s.io
