[program:lwp-fileserver]
command=/usr/local/bin/lwp-fileserver.py
user=lwp
autorestart=unexpected
exitcodes=0
startsecs=1
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
